//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineKredit.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontoDaten
    {
        public int ID { get; set; }
        public string BIC { get; set; }
        public string IBAN { get; set; }
        public Nullable<bool> NeuesKonto { get; set; }
        public string BankName { get; set; }
    
        public virtual Kunde Kunde { get; set; }
    }
}
